# CINEMATIC_DICTIONARY for builder.py - ByteDance Directorial Formula (Parameter Expansion Seedance 2.0)
# Generated for insertion into builder.py

CINEMATIC_DICTIONARY = {
    'Wide Shot': 'The camera frames a broad field of view; the subject occupies a small portion of the frame with the environment and spatial layout clearly visible.',
    'Medium Shot': 'The camera frames the subject from approximately waist up; the subject fills a moderate portion of the frame with limited environment visible.',
    'Medium Close-up': 'The camera frames the subject from approximately chest up; the frame boundary cuts off at mid-chest, excluding most of the surrounding environment.',
    'Close-up': 'The camera frames the subject tightly, filling the frame strictly with the subject\'s face and shoulders, cutting off the surrounding environment.',
    'Big Close-up': 'The camera frames the face only from forehead to chin; the frame excludes the rest of the body and background.',
    'Extreme Close-up': 'The camera frames a single small detail (e.g. eye, mouth, object) at very close range, filling the frame with that detail only.',
    'Insert': 'The camera frames a specific object or small detail in the scene at close range, filling or dominating the frame with that element.',
    'Two Shot': 'The camera frames two subjects together within the same frame; both are visible simultaneously in the composition.',
    'Japanese Anime (Manga)': 'Cel-shaded or flat shading; high-contrast edges; saturated colors; stylized motion lines or speed effects; exaggerated proportions where specified.',
    'Realistic / Photorealistic': 'Naturalistic rendering with physically accurate material surfaces, correct specular and diffuse reflections, photographic depth of field, and no artistic stylization; lighting behaves as real-world light with natural falloff and color temperature; no filters, no painterly effects, no cel-shading.',
    'Disney-style Animation': 'Soft-edged character design; saturated color palette; smooth motion; idealized proportions; fantasy or period environment as specified.',
    'Pixar-style Animation': '3D-rendered look; detailed textures; stylized but coherent lighting; smooth deformation; saturated or controlled color grading.',
    'Studio Ghibli Style': 'Hand-drawn or hand-drawn-style; detailed environments; soft natural lighting; watercolor-like or painted background treatment.',
    'Cyberpunk': 'Neon lighting against dark backgrounds; rain or wet surfaces; urban environment; high contrast; cool and magenta/blue color accent.',
    'Solarpunk': 'Bright environment; green vegetation and sustainable tech visible; warm natural sunlight; high key or balanced exposure.',
    'Dark Fantasy': 'Desaturated or muted palette; low-key lighting; deep shadows; gothic or medieval architectural elements as specified.',
    'Cthulhu / Body Horror': 'Distorted or non-realistic organic textures; green or yellow color tint; unusual camera angles or lens distortion.',
    'Oil Painting': 'Visible brushstroke or paint texture; blended color; chiaroscuro lighting; image resembles a painted surface.',
    'Japanese Drama (Little Forest Style)': 'Soft natural daylight; muted or pastel color palette; clean composition; minimal set elements.',
    'Noir': 'High-contrast low-key lighting; deep shadows; harsh silhouettes; limited fill.',
    'Dreamy': 'Soft diffused lighting; shallow depth of field; blooming or halation on highlights.',
    'Documentary / Neutral': 'Naturalistic lighting; eye-level or neutral camera height; stable or subtle handheld; no stylized color grade.',
    'Epic': 'Wide field of view; high or sweeping camera positions; deep focus; large scale of environment in frame.',
    'Optimistic': 'High-key balanced lighting with warm color temperature around 4500K; open wide or medium-wide framing with upward camera angles; saturated, bright color palette with clear sky or open environment; compositions suggesting space, possibility, and forward momentum.',
    'Melancholic': 'Soft diffused overcast lighting with cool desaturated tones; slow, lingering compositions with negative space around the subject; shallow depth of field isolating the subject from muted backgrounds; color palette leaning toward blue-gray with faded contrast.',
    'Tense': 'High-contrast directional lighting with hard-edged shadows cutting across the frame; tight close-up or medium close-up framing compressing the subject; shallow depth of field with slightly unstable handheld micro-jitter; dark areas left unresolved at frame edges.',
    'Romantic': 'Warm diffused golden-hour backlight around 3200K with soft lens bloom on highlights; intimate close-up framing with shallow depth of field and creamy bokeh; gentle, slow camera movement; skin tones rendered warm and smooth with delicate rim lighting.',
    'Mysterious': 'Low-key lighting with large unlit areas and selective pools of light revealing only fragments of the scene; cool color temperature with isolated warm accent; subject partially obscured by shadow, fog, or foreground elements; depth of field used to blur context.',
    'Intimate': 'Tight framing (close-up or medium close-up); warm color temperature; soft lighting; shallow depth of field.',
    'Surreal': 'Unusual lens choice or perspective; non-natural color palette; camera movement or composition that breaks typical spatial logic.',
    'Nostalgic': 'Warm color temperature; soft diffusion or glow; visible film grain or grain emulation.',
    'Urgent': 'Rapid camera movement; handheld or unstable framing; fast shutter or minimal motion blur; high-contrast lighting.',
    'Peaceful': 'Slow camera movement; high-key or balanced lighting; symmetrical or balanced composition.',
    'Heroic': 'Low camera angle; bright, saturated lighting; subject framed to occupy significant portion of frame or dominate composition.',
    '1930s–40s': 'Black-and-white or monochrome; soft-focus on close-ups; hard key light; period-appropriate costume and set.',
    '1950s': 'Technicolor-style saturation; high-key lighting; bright mid-century set and costume; fine grain or clean emulsion look.',
    'Contemporary': 'Present-day setting; modern glass-and-steel architecture, current fashion and technology; neutral-to-cool digital color grading with clean whites; LED and mixed artificial-natural lighting typical of the 2020s; no period stylization applied.',
    '1920s / Art Deco': 'Geometric ornamental architecture with brass, chrome, and marble surfaces; warm sepia-to-amber palette emulating early panchromatic film stock; dramatic chiaroscuro key lighting with hard shadows; jazz-age costume, bobbed hair, and Art Deco interior motifs.',
    '1960s–70s': 'Warm color shift; visible film grain; slightly desaturated or faded print look; zoom lens movement where specified.',
    'Medieval': 'Firelight or candlelight as key; cold or desaturated daylight; rough textures; period costume and architecture.',
    'Victorian': 'Warm candle or gas light; dark wood and deep shadows; formal, symmetrical composition.',
    'Renaissance': 'Chiaroscuro lighting; symmetrical framing; painterly light and shadow; period-appropriate dress and setting.',
    'Ancient': 'Harsh sunlight; sepia or warm earth tones; wide shots of architecture or landscape; period dress and set.',
    'Futuristic': 'Metallic or smooth surfaces; cool blue or neutral white lighting; clean, controlled camera movement.',
    'Retro-futurism': 'Mid-century design elements combined with sci-fi props or sets; stylized color palette; period-plus-future aesthetic.',
    'Timeless / Unspecified': 'Neutral color temperature; clean lighting; no era-specific styling.',
    'RED Komodo': 'Digital cinema sensor; high dynamic range; neutral to warm color science; sharp edge definition.',
    'RED Ranger': 'High-resolution digital cinema sensor; strong shadow detail; wide color depth.',
    'Sony Venice': 'Digital cinema sensor; smooth highlight roll-off; strong low-light performance; wide color gamut.',
    'Sony FX': 'Digital cinema sensor; high dynamic range; low noise in shadows; sharp resolution.',
    'Blackmagic': 'Digital sensor with film-like highlight roll-off; slightly soft contrast; distinct color science.',
    'Canon C70': 'Digital cinema sensor; warm color bias; smooth highlight transition.',
    'Panasonic Varicam': 'Digital cinema sensor; high dynamic range; organic or film-like color rendering.',
    'Film (35mm)': '35mm film emulation; organic grain; halation on highlights; highlight roll-off; color negative style.',
    'Film (16mm)': '16mm film emulation; pronounced grain; softer resolution; color shift toward warm or faded.',
    'Canon K35': 'Vintage lens character; lower contrast; soft flare; warm skin tone bias.',
    'Canon Sumire Prime': 'Smooth bokeh; subtle flare; soft-focus falloff; controlled sharpness.',
    'Canon Cine-Servo': 'Zoom lens; consistent sharpness across frame; smooth zoom mechanics.',
    'Panavision Primo 70': 'Large-format lens; high resolution; smooth focus fall-off; deep depth rendering.',
    'Panavision T Series Anamorphic': 'Anamorphic lens; horizontal blue streak flare; oval bokeh; edge distortion.',
    'Leica Summilux-C': 'High clarity; neutral color; smooth out-of-focus background; shallow depth of field capability.',
    'Leica Thalia': 'Large-format lens; rounded bokeh; dimensional depth rendering.',
    'Angenieux EZ': 'Zoom lens; warm color bias; smooth bokeh.',
    'Angenieux Optimo Style': 'Zoom lens; high sharpness; even contrast; smooth bokeh.',
    'Not specified': 'Default sensor or lens; no specific emulation or character applied.',
    'Digital (no stock)': 'Clean digital image; minimal noise; no grain; neutral color and sharpness.',
    'Kodak 5219 (500T)': 'Tungsten-balanced high-speed film emulation; saturated colors; visible grain; strong shadow detail.',
    'Kodak 5207 (250D)': 'Daylight-balanced film emulation; fine grain; natural contrast; accurate color.',
    'Kodak 5213 (200T)': 'Tungsten slow-speed film emulation; very fine grain; smooth tonal transition; saturated color.',
    'Fuji Eterna': 'Low-contrast film emulation; muted colors; soft highlight roll-off; pastel tone.',
    'Fuji Eterna Vivid': 'Eterna-based emulation with higher saturation and contrast; soft highlight.',
    'Kodak Vision3': 'Modern color negative film emulation; high dynamic range; fine grain; accurate color.',
    'Film emulation (custom)': 'Custom grain, halation, and color shift applied to match a specified film look.',
    'Full Frame': 'Full-frame sensor or gate; wide field of view; shallow depth of field at wide aperture.',
    'Super 35': 'Super 35 mm sensor or gate; standard cinema field of view and depth of field.',
    'Super 16': 'Super 16 mm sensor or gate; narrower field of view; deeper depth of field; more visible grain at same exposure.',
    'Micro Four Thirds': 'Smaller sensor crop; narrower field of view; deeper depth of field at equivalent aperture.',
    'Large format': 'Large sensor or gate; wide field of view; very shallow depth of field; high resolution.',
    'Vista Vision': 'Large-format horizontal gate; high resolution; wide aspect capture.',
    'Natural only': 'Only ambient environmental light (sun, moon, sky) is used; no added artificial fixtures.',
    'Artificial only': 'Only studio or location artificial fixtures are used; no reliance on ambient daylight or moonlight.',
    'Practical (in-frame)': 'Light sources visible within the frame (e.g. desk lamp, candle, screen) contribute to the illumination of the subject.',
    'Mixed natural + artificial': 'Both ambient environmental light and added artificial fixtures contribute to the exposure.',
    'Studio': 'Controlled lighting environment; multiple fixtures; exposure and direction are set for the subject.',
    'Available light': 'Only light already present at the location is used; no added fixtures.',
    'Single source': 'One dominant light source illuminates the subject; direction is well-defined; shadows are hard-edged and fall in one direction.',
    'Multiple sources': 'Several light sources illuminate the scene from different directions; shadows are reduced or filled.',
    'Front Lighting': 'The primary light source is positioned near the camera axis, in front of the subject; shadows fall behind the subject; features appear flatter.',
    'Side Lighting (Cross Lighting)': 'The primary light source is positioned to the side of the subject (approximately 90 degrees from camera axis); one side of the subject is lit, the other in shadow; texture is emphasized.',
    'Backlighting': 'The primary light source is positioned behind the subject; light comes from the opposite side of the subject from the camera; rim or silhouette effect.',
    'Top Lighting': 'The primary light source is positioned above the subject; light travels downward; shadows fall below brows, nose, and chin.',
    'Underlighting (Bottom Light)': 'The primary light source is positioned below the subject; light travels upward; shadows fall upward; facial topography is lit from beneath.',
    'Three-Point Lighting': 'Key light, fill light, and backlight are used; key from front-side, fill from opposite side to soften shadows, backlight from behind to separate subject from background.',
    'Rembrandt Lighting': 'One directional light is placed to the side and above; a triangular patch of light appears on the shadowed cheek.',
    'Butterfly (Paramount) Lighting': 'The key light is placed directly in front of and above the subject; a butterfly-shaped shadow appears under the nose.',
    'High-Key Lighting': 'Bright, even illumination with low ratio of shadow to highlight; minimal dark areas in the frame.',
    'Low-Key Lighting': 'Strong contrast between lit and unlit areas; deep shadows; a small portion of the frame is brightly lit.',
    'Natural daylight': 'Light approximates 5600K daylight; color temperature is cool-neutral; no artificial color cast.',
    'Golden hour': 'Light approximates warm sunlight just after sunrise or before sunset; color temperature is warm (e.g. 3200–4000K); direction is low and lateral.',
    'Hard directional': 'Small or distant light source; shadows are sharp-edged and clearly defined; high contrast at shadow boundaries.',
    'Soft diffused': 'Large or diffused light source; shadows are soft-edged with gradual falloff; low contrast at shadow boundaries.',
    'Low-key (Chiaroscuro)': 'Extreme contrast between bright highlights and near-black shadows; a small lit area against a large dark area.',
    'Neon / Cyberpunk': 'Practical or simulated lights in saturated pink, purple, and blue; color temperature and hue are strongly tinted.',
    'Candlelight': 'Light approximates 1800–2000K; flicker or variation in intensity; warm color cast.',
    'Tyndall Effect (God Rays)': 'Directional light passes through particulate matter (haze, smoke); visible beams or rays are rendered in the frame.',
    'Static': 'The camera is completely locked off on a fixed mount with zero movement or drift; the frame remains perfectly still, forcing the viewer to absorb the scene composition and the action unfolding within it; used for contemplative beats, tableaux, and moments where stillness carries dramatic weight.',
    'Pan': 'Rotation. The camera rotates horizontally on its vertical axis from a fixed tripod position, sweeping the frame left or right across the scene without any physical translation through space; reveals spatial context or follows lateral subject movement.',
    'Follow (Behind)': 'Translation. The camera tracks through space behind the moving subject, maintaining a consistent rear perspective and distance; the subject leads the viewer forward into the environment, building anticipation for what lies ahead.',
    'Lead (Ahead)': 'Translation. The camera moves through space ahead of and facing back toward the approaching subject; the subject walks or moves toward the lens, creating an intimate, confrontational, or revealing dynamic as the environment falls away behind them.',
    'Dolly in': 'Translation. The camera moves physically forward through space toward the subject, steadily moving closer and filling more of the frame with the subject.',
    'Dolly-in': 'Translation. The camera moves physically forward through space toward the subject, steadily moving closer and filling more of the frame with the subject.',
    'Dolly out': 'performs a medium dolly out at eye-level, steadily pulling backward and away from the scene to reveal more of the surrounding environment.',
    'Dolly-out': 'performs a medium dolly out at eye-level, steadily pulling backward and away from the scene to reveal more of the surrounding environment.',
    'Track': 'Translation. The camera moves laterally through space alongside the subject, maintaining a consistent perpendicular distance; the camera body travels on the X or Z axis.',
    'Follow': 'Translation. The camera moves forward or backward through space behind or ahead of the subject, maintaining relative position along the axis of movement.',
    'Rise (Crane Up)': 'Translation. The camera moves vertically upward through space on the Y axis; the camera body gains height.',
    'Fall (Crane Down)': 'Translation. The camera moves vertically downward through space on the Y axis; the camera body loses height.',
    'Whirl': 'Rotation. The camera spins rapidly around its vertical axis in place; the camera body does not change position in space.',
    'Rotate': 'Rotation. The camera rotates on its roll axis; the horizon line tilts while the camera position remains fixed.',
    'Surround (Orbit)': 'Translation plus aim. The camera moves in a circular or arc path around a central point in 3D space while the lens points at the center.',
    'Zoom': 'No translation. The lens focal length changes; the camera position is fixed. Magnification or demagnification without camera movement.',
    'Hitchcock Zoom': 'Translation plus zoom. The camera moves physically forward or backward while the lens zooms in the opposite direction, keeping subject size constant while background perspective shifts.',
    'Bullet Time': 'The subject\'s motion is frozen or heavily slowed; the camera moves through 3D space at normal speed relative to playback.',
    'Extremely Slow': 'The camera moves through space at very low speed, covering a very small physical distance per unit time.',
    'Slow': 'The camera moves through space at low speed, covering a small to moderate physical distance per unit time.',
    'Normal': 'The camera moves through space at a speed comparable to human walking pace.',
    'Fast': 'The camera moves rapidly through space, covering a large physical distance in a short time.',
    'Dynamic': 'The camera alternates between smooth translational movement and rapid rotational pans; speed and direction change frequently.',
    'Time-lapse': 'Frames are captured at long real-world intervals; playback compresses time so that slow motion (e.g. clouds, growth) appears accelerated.',
    'Bust': 'The camera frames the subject from approximately mid-chest upward; the frame boundary cuts off below the chest.',
    'Half-length Portrait': 'The camera frames the subject from the hips up; the frame boundary cuts off at hip level.',
    'Full-length Portrait': 'The camera frames the subject from head to toe within the vertical extent of the frame; the full body is visible.',
    'Eye-level': 'The camera is positioned so that the lens axis is horizontally parallel to the subject\'s eye line; camera height aligns with subject eyes.',
    'High Angle': 'The physical camera is positioned high above the subject, with the lens explicitly tilted and pointing downwards from the top to the bottom toward the subject.',
    'Low Angle': 'The physical camera is positioned very low to the ground, with the lens explicitly tilted and pointing upwards from the bottom to the top toward the subject.',
    'Bird View (Overhead)': 'The camera is positioned directly above the subject; the lens points straight down along the vertical axis (approximately 90 degrees to ground).',
    'Ant Perspective (Worm\'s Eye)': 'The camera is positioned at or very near ground level, with the lens pointing straight up along the vertical axis toward the subject; everything above appears towering and monumental, amplifying scale, power, or menace.',
    'Over-the-shoulder': 'The camera is placed behind and slightly to the side of one subject; the lens looks past that subject\'s shoulder toward a second subject in the frame.',
    'Subjective View (POV)': 'The camera is positioned at the approximate eye position of a character; the lens direction matches the character\'s sight line.',
    'Surveillance View (Fisheye)': 'An ultra-wide-angle or fisheye lens is used; the image is distorted with curved lines and exaggerated field of view.',
    'Telescope View': 'A long focal length (telephoto) is used; the camera is physically distant from the subject; background is compressed and depth of field is shallow.',
    'Peeping Perspective': 'The camera is positioned so that foreground obstructions (e.g. door frame, foliage) partially occlude the frame; the subject is visible through or past the obstruction.',
    'Front View': 'The camera is placed in front of the subject; the lens points at the subject\'s front; the subject faces the camera.',
    'Profile': 'The camera is placed at 90 degrees to the subject; the lens points at the subject\'s side; one side of the face and body is visible.',
    'Half-profile': 'The camera is placed at an angle between front and profile (e.g. 30–45 degrees); the subject is partly turned from the camera.',
    'Back View': 'The camera is placed behind the subject; the lens points at the subject\'s back; the face is not visible.',
    'Top View': 'The camera is positioned directly above the subject; the lens points down; the top of the subject\'s head and the spatial layout below are visible.',
    'Bottom View': 'The camera is positioned directly below the subject; the lens points up; the subject is seen from beneath.',
}
